"""new fields added in User model

Revision ID: e92cfb4f749c
Revises: 6ff8bed582e8
Create Date: 2018-05-01 09:13:52.965274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92cfb4f749c'
down_revision = '6ff8bed582e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('city_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('country_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'country_name')
    op.drop_column('user', 'city_name')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
